version: "3.8"

services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "${SWAGGER_PORT:-8088}:8080"
    environment:
      - URLS_PRIMARY_NAME=${SWAGGER_URLS_PRIMARY_NAME}
      - URLS=${SWAGGER_URLS}